# Generated by Django 4.1.1 on 2022-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('codigo_usuario', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('tipo_usuario', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(max_length=128)),
                ('apellidos', models.TextField(max_length=128)),
                ('email', models.TextField(max_length=128)),
            ],
        ),
    ]
